<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>ev_bringup</name>
  <version>0.0.1</version>
  <description>EV_racing 자율주행 스택 launch 모음</description>
  <maintainer email="kbc6710@gmail.com">bongpodoal</maintainer>
  <license>Apache-2.0</license>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ev_perception</exec_depend>
  <exec_depend>ev_planning</exec_depend>
  <exec_depend>ev_arduino_bridge</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
